### ISSUE TITLE
可以支持api调用吗

### ISSUE THREAD

**Issue by hausen1012** [txstc55/ugly-avatar#10]

**Comment by opzpy123** [comment]
+1

**Comment by txstc55** [comment]
你们要么等一下5月19以后。。。有个deadline

**Comment by shiny** [comment]
> 你们要么等一下5月19以后。。。有个deadline

或者能不能生成一个字符串，类似 uuid，每次应用这个字符串就会出现同样的头像。这样不用存图片，只要存这个字符串，前端渲染就行。

**Comment by txstc55** [comment]
> > 你们要么等一下5月19以后。。。有个deadline
> 
> 或者能不能生成一个字符串，类似 uuid，每次应用这个字符串就会出现同样的头像。这样不用存图片，只要存这个字符串，前端渲染就行。

那不如直接拿svg好了，本来就是一个svg渲染的

**Comment by shiny** [comment]
场景：我想为所有用户生成一个默认头像；同一个用户每次都看到同一个随机头像；不同用户头像不一样。

如果是个seeder，比如用户的uid，就可以直接复用现有的值。在后端不需要处理任何功能，直接交给前端渲染。

**Comment by txstc55** [comment]
> 场景：我想为所有用户生成一个默认头像；同一个用户每次都看到同一个随机头像；不同用户头像不一样。
> 
> 如果是个seeder，比如用户的uid，就可以直接复用现有的值。在后端不需要处理任何功能，直接交给前端渲染。

那如果是api的话只要加个seed进去就行了，你说的如果直接integrate到网站里面需要你把整个生成器放到你的网站上，然后放进去seed出一张头像

**Comment by mamumu123** [comment]
@hausen1012 @opzpy123 @shiny 
我实现了这个 issue 中提到的功能，不过由于改动过大，只能新起一个项目，而无法合并入这个项目。
可以用来参考思路：

1. 增设了 API 接口，可以直接返回随机生成的头像；
2. 添加了 'id' 和 'username' 参数，通过固定这两个参数，可以确保返回的头像保持一致；
3. 增加了 'bg_color' 参数，通过这个参数，可以确保头像的背景色是固定的颜色值；
4. 增加了 'w' 和 'h' 参数，通过这个参数，可以指定返回图片的宽度和高度；

仓库地址：https://github.com/mamumu123/next-api-share
### api demo

#### 随机返回
https://next-api-share.vercel.app/api/face

#### 固定背景色
https://next-api-share.vercel.app/api/face?bg_color=rgb(245,245,220)

https://next-api-share.vercel.app/api/face?bg_color=red


#### 固定返回值
https://next-api-share.vercel.app/api/face?id=666

https://next-api-share.vercel.app/api/face?username=john

#### 固定宽度或高度
https://next-api-share.vercel.app/api/face?w=400&h=400

**Comment by txstc55** [comment]
> @hausen1012 @opzpy123 @shiny 我实现了这个 issue 中提到的功能，不过由于改动过大，只能新起一个项目，而无法合并入这个项目。 可以用来参考思路：
> 
> 1. 增设了 API 接口，可以直接返回随机生成的头像；
> 2. 添加了 'id' 和 'username' 参数，通过固定这两个参数，可以确保返回的头像保持一致；
> 3. 增加了 'bg_color' 参数，通过这个参数，可以确保头像的背景色是固定的颜色值；
> 4. 增加了 'w' 和 'h' 参数，通过这个参数，可以指定返回图片的宽度和高度；
> 
> 仓库地址：https://github.com/mamumu123/next-api-share
> 
> ### api demo
> #### 随机返回
> https://next-api-share.vercel.app/api/face
> 
> #### 固定背景色
> https://next-api-share.vercel.app/api/face?bg_color=rgb(245,245,220)
> 
> https://next-api-share.vercel.app/api/face?bg_color=red
> 
> #### 固定返回值
> https://next-api-share.vercel.app/api/face?id=666
> 
> https://next-api-share.vercel.app/api/face?username=john
> 
> #### 固定宽度或高度
> https://next-api-share.vercel.app/api/face?w=400&h=400

这就尴尬了，我本来还想自己做来着

**Comment by shiny** [comment]
> @hausen1012 @opzpy123 @shiny 我实现了这个 issue 中提到的功能，不过由于改动过大，只能新起一个项目，而无法合并入这个项目。 可以用来参考思路：
> 
>     1. 增设了 API 接口，可以直接返回随机生成的头像；
> 
>     2. 添加了 'id' 和 'username' 参数，通过固定这两个参数，可以确保返回的头像保持一致；
> 
>     3. 增加了 'bg_color' 参数，通过这个参数，可以确保头像的背景色是固定的颜色值；
> 
>     4. 增加了 'w' 和 'h' 参数，通过这个参数，可以指定返回图片的宽度和高度；
> 
> 
> 仓库地址：https://github.com/mamumu123/next-api-share
> ### api demo
> #### 随机返回
> 
> https://next-api-share.vercel.app/api/face
> #### 固定背景色
> 
> https://next-api-share.vercel.app/api/face?bg_color=rgb(245,245,220)
> 
> https://next-api-share.vercel.app/api/face?bg_color=red
> #### 固定返回值
> 
> https://next-api-share.vercel.app/api/face?id=666
> 
> https://next-api-share.vercel.app/api/face?username=john
> #### 固定宽度或高度
> 
> https://next-api-share.vercel.app/api/face?w=400&h=400

建议添加个 License。我会去尝试下。

**Comment by txstc55** [comment]
@mamumu123 @shiny 只要别commercial use就可以了

**Comment by mamumu123** [comment]
> > @hausen1012 @opzpy123 @shiny 我实现了这个 issue 中提到的功能，不过由于改动过大，只能新起一个项目，而无法合并入这个项目。 可以用来参考思路：
> > ```
> > 1. 增设了 API 接口，可以直接返回随机生成的头像；
> > 
> > 2. 添加了 'id' 和 'username' 参数，通过固定这两个参数，可以确保返回的头像保持一致；
> > 
> > 3. 增加了 'bg_color' 参数，通过这个参数，可以确保头像的背景色是固定的颜色值；
> > 
> > 4. 增加了 'w' 和 'h' 参数，通过这个参数，可以指定返回图片的宽度和高度；
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 仓库地址：https://github.com/mamumu123/next-api-share
> > ### api demo
> > #### 随机返回
> > https://next-api-share.vercel.app/api/face
> > #### 固定背景色
> > https://next-api-share.vercel.app/api/face?bg_color=rgb(245,245,220)
> > https://next-api-share.vercel.app/api/face?bg_color=red
> > #### 固定返回值
> > https://next-api-share.vercel.app/api/face?id=666
> > https://next-api-share.vercel.app/api/face?username=john
> > #### 固定宽度或高度
> > https://next-api-share.vercel.app/api/face?w=400&h=400
> 
> 建议添加个 License。我会去尝试下。

done, 头像生成部分同原作者 License

**Comment by mamumu123** [comment]
> > @hausen1012 @opzpy123 @shiny 我实现了这个 issue 中提到的功能，不过由于改动过大，只能新起一个项目，而无法合并入这个项目。 可以用来参考思路：
> > 
> > 1. 增设了 API 接口，可以直接返回随机生成的头像；
> > 2. 添加了 'id' 和 'username' 参数，通过固定这两个参数，可以确保返回的头像保持一致；
> > 3. 增加了 'bg_color' 参数，通过这个参数，可以确保头像的背景色是固定的颜色值；
> > 4. 增加了 'w' 和 'h' 参数，通过这个参数，可以指定返回图片的宽度和高度；
> > 
> > 仓库地址：https://github.com/mamumu123/next-api-share
> > ### api demo
> > #### 随机返回
> > https://next-api-share.vercel.app/api/face
> > #### 固定背景色
> > https://next-api-share.vercel.app/api/face?bg_color=rgb(245,245,220)
> > https://next-api-share.vercel.app/api/face?bg_color=red
> > #### 固定返回值
> > https://next-api-share.vercel.app/api/face?id=666
> > https://next-api-share.vercel.app/api/face?username=john
> > #### 固定宽度或高度
> > https://next-api-share.vercel.app/api/face?w=400&h=400
> 
> 这就尴尬了，我本来还想自己做来着

我这个扩展由于改动比较大，所以无法提 mr；如果 owner 有想法，可以重新实现呢。

**Comment by txstc55** [comment]
我看了，你基本用nextjs重写了一遍组装逻辑，能用着就用呗，只不过每次我这边更新你就要重新复制黏贴一遍代码也有点烦，以后我有空了再布置到vercel吧

**Comment by shiny** [comment]
> @mamumu123 @shiny 只要别commercial use就可以了

想要请教下，我打算把这个功能用在自己的短网址服务上，为用户设置默认头像；用户可能会订阅我们的服务。
以这种情况，按我对 README.md 里说明的理解，应该是允许使用的？

**Comment by txstc55** [comment]
@shiny 这个是可以的，不过如果可以的话请同时cite 我和 @mamumu123

**Comment by txstc55** [comment]
@shiny 不能商用的逻辑是不能单用这个头像生成的服务去收费，比如把它做成nft，或者说生成多少张图要收费这种。如果我当时有收费这种想法我就不会开源了

**Comment by shiny** [comment]
> @shiny 这个是可以的，不过如果可以的话请同时cite 我和 @mamumu123

感谢，没问题。
