### ISSUE TITLE
能不能做个选择性别的功能

### ISSUE THREAD

**Issue by galenjiang** [txstc55/ugly-avatar#11]

**Comment by txstc55** [comment]
你怎么区分男女呢，男的可以有长发，女的也可以有短发

**Comment by galenjiang** [comment]
> 你怎么区分男女呢，男的可以有长发，女的也可以有短发

重新看了下，有些头像比较中性，有些看起来也有点女性特征，确实也可以用。
另外可以考虑增加个辫子的特征。
