### ISSUE TITLE
可以添加一个野原广志砖头脸的形状么？

### ISSUE THREAD

**Issue by Antisunny** [txstc55/ugly-avatar#9]
我这脸型是长方形的，期待这种脸型

**Comment by txstc55** [comment]
我会想想，因为现在很多的计算是bound在蛋型的脸上的，比如我蛋的45度角可以，或者说整个蛋型的1/4处是眼睛，但是长方形的1/4是头顶，所以需要改很多，但是是个不错的想法

**Comment by txstc55** [comment]
@Antisunny 加好了，现在有0.03的概率是一个长方形（很正方的那种），0.63的概率是和原来一样，其他时间是一个圆筒形
